apiVersion: v1
kind: Service
metadata:
  name: gadget-store-svc #TODO: to specify your service name
  labels:
    app: gadget-store-svc
spec:
  selector:
    app: gadget-store-app #TODO: change label selector to match your backend pod
  ports:
  - protocol: TCP
    name: http
    port: 3000 #TODO: choose an unique port on each node to avoid port conflict
    targetPort: 3000
  type: LoadBalancer
#  type: LoadBalancer