apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gadget-store-app
  labels:
    app: gadget-store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gadget-store-app
  template:
    metadata:
      labels:
        app: gadget-store-app
    spec:
    #  nodeSelector:
    #    env: test-team
      containers:
      - name: gadget-store-app
        image: jawnlim89/gadget-store-docker # replace it with your exactly <image_name:tags>
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"